spring.application.name=CommUnity
spring.mongodb.uri=mongodb://localhost:27017/communitydb
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${gmailId}
spring.mail.password=${Code}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
logging.level.org.springframework.security=DEBUG